// ─────────────────────────────────────────────────────────
// DATA: All modules, sections, and goals
// Shared between Lektionsopbygger and ModulFlow
// ─────────────────────────────────────────────────────────

export const MODULES_RAW = [
  {
    id: 1, title: "Grundlæggende trafikforståelse", color: "#2563EB",
    theory: 7, practice: 0, selfStudyAllowed: [3, 6],
    sections: [
      { id: "0", title: "Indledning", type: "theory", mustBeFirst: true,
        goals: ["Køreuddannelsens formål og grundprincipper", "Teori før praksis-princippet", "Progression fra lettere til sværere", "Aktiv dialog ved holdningsbearbejdelse"] },
      { id: "10.1.1", title: "Køreundervisning mv.", type: "theory", mustBeFirst: true,
        goals: ["Alderskrav og helbredsbetingelser", "Krav om førstehjælpskursus", "Undervisningens omfang og form", "Modulplanens funktion"] },
      { id: "3", title: "Køretøjers manøvreegenskaber", type: "theory", selfStudy: true,
        goals: ["3.1.1 Fartegenskaber", "3.1.2 Styreegenskaber", "3.1.3 Orienteringsvilkår", "3.2.1–3.2.8 Forskellige køretøjer"] },
      { id: "4", title: "Trafikantadfærd", type: "theory",
        goals: ["4.1 Opfattelse og reaktion", "4.2 Syn og bevægelse", "4.3 Afstand og hastighed", "4.4 Køreevne og helbred", "4.5 Andre trafikanters adfærd", "4.6 Bedømmelse af andre", "4.7 Egne holdninger"] },
      { id: "5.1", title: "Vejenes sikkerhedsmæssige udformning", type: "theory",
        goals: ["5.1.1 Grænser for vejes sikkerhed", "5.1.2 Benyttelse af vejene"] },
      { id: "6(1)", title: "Grundregler for færdsel (uddrag)", type: "theory", selfStudy: true,
        goals: ["6.1 Anvisninger for færdslen", "6.2.1 Grundregler", "6.2.2 Fare og ulempe", "6.2.9 Færdselsulykke", "6.2.10 Forsikringspligt", "6.2.11 Overladelse af køretøj"] },
    ],
  },
  {
    id: 2, title: "Forberedende teori- og kørselsmodul", color: "#059669",
    theory: 5, practice: 3, selfStudyAllowed: [1, 6],
    sections: [
      { id: "1", title: "Køretøjets indretning, udstyr, betjening", type: "theory", selfStudy: true,
        goals: ["1.1 Betjeningsudstyr og instrumenter", "1.1.6 Førerassistentsystemer", "1.2 Lovbestemmelser", "1.2.6 Energi- og miljørigtig kørsel", "1.2.10 Særlige køretøjer", "1.3 Køretøjets dokumenter"] },
      { id: "2", title: "Manøvrer på lukket øvelsesplads", type: "practice",
        goals: ["2.1 Forberedelse til kørsel", "2.2 Igangsætning og standsning", "2.3 Kørsel i 8-tal", "2.4 Forlæns/baglæns målbremsning", "2.5 Baglæns kørsel med svingning", "2.6 Forlæns/baglæns slalom", "2.7 Parkering ved vejkant", "2.8 Kørsel i 2. gear, højresving", "2.9 Vending"] },
      { id: "5.2", title: "Risikoforhold ved vejene", type: "theory",
        goals: ["5.2.1 Kendetegn på risikoforhold", "5.2.2 Vejens omgivelser", "5.2.3 Vejens udstyr", "5.2.4 Vejens forløb", "5.2.5 Vejens brug", "5.2.6 Vejens type"] },
      { id: "6(2)", title: "Grundregler for færdsel (fortsat)", type: "theory", selfStudy: true,
        goals: ["6.2.3 Signalgivning", "6.2.4 Tegngivning", "6.2.5 Brug af lys", "6.2.6 Fri passage", "6.2.7 Gods mv.", "6.2.8 Motorstop og slæbning"] },
    ],
  },
  {
    id: 3, title: "Grundlæggende kørsel på vej", color: "#D97706",
    theory: 8, practice: 6, selfStudyAllowed: [],
    gateIds: ["7.1", "7.2", "7.3", "7.6", "7.7", "7.8"],
    gateBlockedIds: ["7.4", "7.10", "7.11", "7.12", "7.13", "7.14", "7.15"],
    sections: [
      { id: "7.1", title: "Igangsætning og standsning", type: "both", mustBeFirst: true,
        goals: ["7.1.1 Ulykker", "7.1.2 Risikoforhold", "7.1.3 Orientering", "7.1.4 Manøvre", "7.1.5 Lovbestemmelser"] },
      { id: "7.2", title: "Placering under ligeudkørsel", type: "both", mustBeFirst: true,
        goals: ["7.2.1 Ulykker", "7.2.2 Risikoforhold", "7.2.3 Orientering", "7.2.4 Manøvre"] },
      { id: "7.3", title: "Hastighed under ligeudkørsel", type: "both", mustBeFirst: true,
        goals: ["7.3.1 Ulykker", "7.3.2 Risikoforhold", "7.3.3 Orientering", "7.3.4 Manøvre", "7.3.5 Lovbestemmelser"] },
      { id: "7.6", title: "Passage af holdende køretøjer", type: "both", mustBeFirst: true,
        goals: ["7.6.1 Ulykker", "7.6.2 Risikoforhold", "7.6.3 Orientering", "7.6.4 Manøvre"] },
      { id: "7.7", title: "Møde", type: "both", mustBeFirst: true,
        goals: ["7.7.1 Ulykker", "7.7.2 Risikoforhold", "7.7.3 Orientering", "7.7.4 Manøvre", "7.7.5 Lovbestemmelser"] },
      { id: "7.8", title: "Kørsel foran/efter andre", type: "both", mustBeFirst: true,
        goals: ["7.8.1 Ulykker", "7.8.2 Risikoforhold", "7.8.3 Orientering", "7.8.4 Manøvre", "7.8.5 Lovbestemmelser"] },
      { id: "7.4", title: "Vognbaneskift", type: "both", context: "Mindre trafikeret vej",
        goals: ["7.4.1 Ulykker", "7.4.2 Risikoforhold", "7.4.3 Orientering", "7.4.4 Manøvre", "7.4.5 Lovbestemmelser"] },
      { id: "7.10", title: "Trafiksanerede områder", type: "both",
        goals: ["7.10.1 Ulykker", "7.10.2 Risikoforhold", "7.10.3 Orientering", "7.10.4 Manøvre", "7.10.5 Lovbestemmelser"] },
      { id: "7.11", title: "Fremkørsel mod kryds", type: "both", context: "Mindre trafikeret vej",
        goals: ["7.11.1 Ulykker", "7.11.2 Risikoforhold", "7.11.3 Orientering", "7.11.4 Manøvre"] },
      { id: "7.12", title: "Ligeudkørsel i kryds", type: "both", context: "Mindre trafikeret vej",
        goals: ["7.12.1 Ulykker", "7.12.2 Risikoforhold", "7.12.3 Orientering", "7.12.4 Manøvre"] },
      { id: "7.13", title: "Højresving i kryds", type: "both", context: "Mindre trafikeret vej",
        goals: ["7.13.1 Ulykker", "7.13.2 Risikoforhold", "7.13.3 Orientering", "7.13.4 Manøvre"] },
      { id: "7.14", title: "Venstresving i kryds", type: "both", context: "Mindre trafikeret vej",
        goals: ["7.14.1 Ulykker", "7.14.2 Risikoforhold", "7.14.3 Orientering", "7.14.4 Manøvre"] },
      { id: "7.15", title: "Kørsel i rundkørsel", type: "both", context: "Mindre trafikeret vej",
        goals: ["7.15.1 Ulykker", "7.15.2 Risikoforhold", "7.15.3 Orientering", "7.15.4 Manøvre"] },
    ],
  },
  {
    id: 4, title: "Udvidet kørsel på vej", color: "#E0599B",
    theory: 9, practice: 6, practiceNote: "heraf min. 1 i mørke", selfStudyAllowed: [10],
    sections: [
      { id: "7.4*", title: "Vognbaneskift (tæt trafik)", type: "practice", context: "Genoptaget fra M3" },
      { id: "7.11*", title: "Fremkørsel mod kryds (tæt trafik)", type: "practice", context: "Genoptaget fra M3" },
      { id: "7.12*", title: "Ligeudkørsel i kryds (tæt trafik)", type: "practice", context: "Genoptaget fra M3" },
      { id: "7.13*", title: "Højresving i kryds (tæt trafik)", type: "practice", context: "Genoptaget fra M3" },
      { id: "7.14*", title: "Venstresving i kryds (tæt trafik)", type: "practice", context: "Genoptaget fra M3" },
      { id: "7.15*", title: "Kørsel i rundkørsel (tæt trafik)", type: "practice", context: "Genoptaget fra M3" },
      { id: "7.5", title: "Vending og baglænskørsel", type: "both",
        goals: ["7.5.1 Ulykker", "7.5.2 Risikoforhold", "7.5.3 Orientering", "7.5.4 Manøvre", "7.5.5 Lovbestemmelser"] },
      { id: "7.9", title: "Overhaling", type: "both",
        goals: ["7.9.1 Ulykker", "7.9.2 Risikoforhold", "7.9.3 Orientering", "7.9.4 Manøvre", "7.9.5 Lovbestemmelser"] },
      { id: "7.16", title: "Kørsel på motorvej", type: "both",
        goals: ["7.16.1 Ulykker", "7.16.2 Risikoforhold", "7.16.3 Orientering", "7.16.4 Manøvre", "7.16.5 Lovbestemmelser", "7.16.6 Motortrafikvej"] },
      { id: "7.17", title: "Kørsel ved siden af andre", type: "both",
        goals: ["7.17.1 Ulykker", "7.17.2 Risikoforhold", "7.17.3 Orientering", "7.17.4 Manøvre"] },
      { id: "7.18", title: "Standsning og parkering", type: "both",
        goals: ["7.18.1 Ulykker", "7.18.2 Risikoforhold", "7.18.3 Orientering", "7.18.4 Manøvre", "7.18.5 Lovbestemmelser"] },
      { id: "7.19", title: "Kørsel i mørke", type: "both", highlight: "Min. 1 lektion i mørke",
        goals: ["7.19.1 Ulykker", "7.19.2 Risikoforhold", "7.19.3 Orientering", "7.19.4 Manøvre", "7.19.5 Lovbestemmelser"] },
      { id: "7.20", title: "Kørsel i tunnel", type: "both",
        goals: ["7.20.1 Ulykker", "7.20.2 Risikoforhold", "7.20.3 Orientering", "7.20.4 Manøvre"] },
      { id: "7.21", title: "Kørsel ved letbane", type: "both",
        goals: ["7.21.1 Ulykker", "7.21.2 Risikoforhold", "7.21.3 Orientering"] },
      { id: "8", title: "Særlige risikoforhold", type: "theory",
        goals: ["8.1.1 Alkohol", "8.1.2 Narkotika", "8.1.3 Hastighed", "8.1.4 Sikkerhedssele", "8.2.1 Opmærksomhed", "8.2.2 Adfærd", "8.2.3 Kørselskompetencer"] },
      { id: "10(2)", title: "Kørekortregler (fortsat)", type: "theory", selfStudy: true,
        goals: ["10.1.2 Indstilling til køreprøve", "10.2 Køreprøvens gennemførelse", "10.3 Lovbestemmelser om kørekort"] },
    ],
  },
  {
    id: 5, title: "Afsluttende modul", color: "#7C3AED",
    theory: 1, practice: 9, practiceNote: "heraf 4 på KTA", selfStudyAllowed: [9],
    sections: [
      { id: "9", title: "Manøvrer på køreteknisk anlæg", type: "both", selfStudy: true, highlightPractice: "4 obligatoriske lektioner på KTA",
        goals: ["9.1 Vejgreb og belæsning", "9.2 Hastighed og bremselængde", "9.3 Hindringer og slalom", "9.4 Genvinding af vejgreb", "9.5 Kørsel over høj vejkant"] },
      { id: "7.22", title: "Afsluttende øvelseskørsel", type: "practice", repeatable: true,
        goals: ["7.22.1 Bilens indretning mv.", "7.22.2 Trafikantadfærd", "7.22.3 Vejforhold", "Selvstændig planlægning"] },
    ],
  },
];
